"""add employer_id to user

Revision ID: 427fd7b5bda2
Revises: 38b6abca3eb6
Create Date: 2026-04-26 23:34:13.838443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427fd7b5bda2'
down_revision: Union[str, None] = '38b6abca3eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employer_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['employer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'employer_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
