"""add rating to incidents

Revision ID: a571f28b1234
Revises: 427fd7b5bda2
Create Date: 2026-06-08 04:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a571f28b1234'
down_revision: Union[str, None] = '427fd7b5bda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('rating', sa.Integer(), nullable=True, comment='Puntuación 1 a 5'))
    op.add_column('incidents', sa.Column('review_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'review_comment')
    op.drop_column('incidents', 'rating')
    # ### end Alembic commands ###
