"""Init_Supabase

Revision ID: bb0e7a84151c
Revises: 
Create Date: 2026-04-18 20:46:52.675604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'bb0e7a84151c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('cars_license_plate_key'), 'cars', type_='unique')
    op.create_index(op.f('ix_cars_license_plate'), 'cars', ['license_plate'], unique=True)
    op.alter_column('incident_photos', 'incident_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('incident_photos', 'storage_url',
               existing_type=sa.TEXT(),
               comment='URL en S3 / storage',
               existing_nullable=False)
    op.alter_column('incident_photos', 'ai_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Payload JSON del modelo de IA',
               existing_nullable=True)
    op.alter_column('incident_photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'incident_location',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, _spatial_index_reflected=True),
               comment='Coordenadas GPS donde ocurrió el incidente',
               existing_nullable=False)
    op.alter_column('incidents', 'severity_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('incidents', 'reported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_incidents_location'), table_name='incidents', postgresql_using='gist')
    op.create_index('idx_incidents_incident_location', 'incidents', ['incident_location'], unique=False, postgresql_using='gist')
    op.alter_column('invoices', 'cuf',
               existing_type=sa.TEXT(),
               comment='Código Único de Factura',
               existing_nullable=True)
    op.alter_column('invoices', 'cufd',
               existing_type=sa.TEXT(),
               comment='Código Único de Facturación Diaria',
               existing_nullable=True)
    op.alter_column('invoices', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_methods', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='QR | Transferencia | Efectivo',
               existing_nullable=False)
    op.alter_column('payment_methods', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'BOB'::character varying"))
    op.alter_column('payments', 'qr_code_image',
               existing_type=sa.TEXT(),
               comment='URL del QR generado',
               existing_nullable=True)
    op.alter_column('payments', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_orders', 'current_mechanic_location',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               comment='Ubicación GPS del mecánico en ruta al incidente',
               existing_nullable=True)
    op.create_index('idx_service_orders_current_mechanic_location', 'service_orders', ['current_mechanic_location'], unique=False, postgresql_using='gist')
    op.alter_column('status_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_data', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'current_location',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               comment='Ubicación GPS en tiempo real (WGS84)',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_location'), table_name='users', postgresql_using='gist')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('idx_users_current_location', 'users', ['current_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('workshops', 'tax_id',
               existing_type=sa.VARCHAR(length=50),
               comment='NIT en Bolivia',
               existing_nullable=True)
    op.alter_column('workshops', 'geom',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, _spatial_index_reflected=True),
               comment='Ubicación geográfica del taller (WGS84)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshops', 'geom',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, _spatial_index_reflected=True),
               comment=None,
               existing_comment='Ubicación geográfica del taller (WGS84)',
               existing_nullable=False)
    op.alter_column('workshops', 'tax_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='NIT en Bolivia',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_current_location', table_name='users', postgresql_using='gist')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_location'), 'users', ['current_location'], unique=False, postgresql_using='gist')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'current_location',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               comment=None,
               existing_comment='Ubicación GPS en tiempo real (WGS84)',
               existing_nullable=True)
    op.alter_column('tax_data', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('status_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_service_orders_current_mechanic_location', table_name='service_orders', postgresql_using='gist')
    op.alter_column('service_orders', 'current_mechanic_location',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               comment=None,
               existing_comment='Ubicación GPS del mecánico en ruta al incidente',
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('payments', 'qr_code_image',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='URL del QR generado',
               existing_nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'BOB'::character varying"))
    op.alter_column('payment_methods', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('payment_methods', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='QR | Transferencia | Efectivo',
               existing_nullable=False)
    op.alter_column('invoices', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'cufd',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Código Único de Facturación Diaria',
               existing_nullable=True)
    op.alter_column('invoices', 'cuf',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Código Único de Factura',
               existing_nullable=True)
    op.drop_index('idx_incidents_incident_location', table_name='incidents', postgresql_using='gist')
    op.create_index(op.f('idx_incidents_location'), 'incidents', ['incident_location'], unique=False, postgresql_using='gist')
    op.alter_column('incidents', 'reported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('incidents', 'severity_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('incidents', 'incident_location',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, _spatial_index_reflected=True),
               comment=None,
               existing_comment='Coordenadas GPS donde ocurrió el incidente',
               existing_nullable=False)
    op.alter_column('incident_photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incident_photos', 'ai_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Payload JSON del modelo de IA',
               existing_nullable=True)
    op.alter_column('incident_photos', 'storage_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='URL en S3 / storage',
               existing_nullable=False)
    op.alter_column('incident_photos', 'incident_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_cars_license_plate'), table_name='cars')
    op.create_unique_constraint(op.f('cars_license_plate_key'), 'cars', ['license_plate'], postgresql_nulls_not_distinct=False)
    op.alter_column('cars', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
